### ISSUE TITLE
Habit Reminder

### ISSUE THREAD

**Issue by LydiaVuj** [chingu-voyages/bears-project-8#12]
On the Habit Form, the user should have the option of setting goal reminders and choosing the way the app would send him the reminder

Time:
- Daily Reminder
- Weekly Reminder
- Monthly Reminder

Notification:
- Email
- In-App

**Comment by arielbk** [comment]
Is this issue related to just the API route to enable this, or the actual frontend component within the form? The API and FE tags together are confusing. Please clarify 😀

**Comment by Puritanic** [comment]
@arielbk @LydiaVuj  I think that this should be an Epic on its own. We need a mail server for the backend to send email reminders and we need to set up some kind of push notifications, or/and regular in-app notifications.

We will also need some kind of email templates for this.

I've used Sendgrid for something like this before, and its PITA to set up... Never worked with push notifications API before :/

**Comment by LydiaVuj** [comment]
do we still want to go with all the notification types?

**Comment by LydiaVuj** [comment]
i opened an Epic for this. closing this issue
