### ISSUE TITLE
User - Login

### ISSUE THREAD

**Issue by Puritanic** [chingu-voyages/bears-project-8#16]
**As a** User **I want** to log in to the application with my credentials.

##### Acceptance Criteria

If I create a POST request to /login route with correct credentials I should be authorized to log in.

`/login` route should be created with logic to authorize user if correct credentials are passed down with the request, or to reject the request if those are incorrect.

##### Notes

I was thinking about using JWT with BCrypt for user authentication. Email, password authentication for now and later we can add social login feature.

**Comment by LydiaVuj** [comment]
why not use passport?

**Comment by Puritanic** [comment]
Why not both? 😄
