### ISSUE TITLE
Dashboard layout

### ISSUE THREAD

**Issue by LydiaVuj** [chingu-voyages/bears-project-8#28]
Web frame and design

**Comment by arielbk** [comment]
There is a lot of information that we want to display on this page, while still keeping it minimal and with a light feeling.

I think that we could do this by displaying just the important information so things are easy to see at a glance and intuitive, with more detailed information there when its needed.

Key pieces of the habit could be shown, with more details expanded when the user clicks on the habit.

**Comment by arielbk** [comment]
Some ideas of what should (or could) contain:
-	Due habits
-	Upcoming habits
-	Edit habit
-	Log habit
-	Logbook *(habits that have been logged – from here they could also be unlogged if it was a mistake)*
-	Insights *(this is where we could have data visualisations of habit logging over time)*
-	Filter habits by tags, difficulty, and/or habit type

**Comment by arielbk** [comment]
Here is a prototype link:
https://www.figma.com/proto/0cYMH3IwMovJxuaUNrVustGm/Dashboard?node-id=79%3A581&viewport=-385%2C274%2C0.5&scaling=min-zoom

You can click on the first habit in the list to see what it would look like expanded.
