### ISSUE TITLE
Habit form layout

### ISSUE THREAD

**Issue by LydiaVuj** [chingu-voyages/bears-project-8#29]
Web frame and design

**Comment by Puritanic** [comment]
@arielbk Can you add a link to what we're supposed to review here? I know it's on Figma but for documenting purposes it would be better if you include it here too.

**Comment by arielbk** [comment]
@Puritanic yup, good idea.

Link to the prototype is https://www.figma.com/proto/SCusPxFWtAxZAXmBpTk7tHrW/Habit-Form

**Comment by Puritanic** [comment]
Thank you. 
I took a look at the design and it looks really good, I appreciate the work you've put into this :) and I think that this should be more than enough for kickstarting frontend work.
